kind: pipeline
type: docker
name: build and push

volumes:
- name: docker_socket
  host:
    path: /var/run/docker.sock

steps:
- name: build
  image: docker:latest
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  commands:
  - docker build -t mynginx .
  when:
    event:
    - push
    branch:
    - main

- name: login
  image: plugins/docker:latest
  settings:
    username: chaikair
    password: 389609066
  when:
    event:
    - push
    branch:
    - main

- name: push
  image: plugins/docker:latest
  settings:
    repository: chaikair/mynginx
    tags: [latest]
  when:
    event:
    - push
    branch:
    - main
